#!/usr/bin/env bash

echo ""
echo ""
echo rm -r var/log

docker-compose -f docker-compose.yml exec php-fpm rm -r var/log

echo ""
echo ""
echo php bin/phpunit $*
echo ""
echo ""

docker-compose -f docker-compose.yml exec php-fpm php bin/phpunit $*

docker-compose -f docker-compose.yml exec php-fpm chmod 777 -R var/
