#!/usr/bin/env sh

# Remove config file and restart nginx and php-fpm

docker-compose -f docker-compose.yml exec php-fpm rm /usr/local/etc/php/conf.d/zzz_custom_zz.ini && docker-compose -f /home/pablito/Projects/RebilliaServer/docker_api_rebillia/docker-compose.yml exec www nginx -s reload
